/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.openhie.openpixpdq.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.7 2013-12-09T11:35:29.460-05:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(serviceName = "PIXManager_Service", portName = "PIXManager_Port_Soap12", targetNamespace = "urn:org:openhie:openpixpdq:services", wsdlLocation = "classpath:PIXPDQManager.wsdl", endpointInterface = "org.openhie.openpixpdq.services.PIXManagerPortType")
public class PIXManagerPortTypeImpl implements PIXManagerPortType {

	private static final Logger LOG = Logger
			.getLogger(PIXManagerPortTypeImpl.class.getName());
	protected static org.hl7.v3.types.PRPAIN201310UV02 returnedValueOfPixManagerPRPAIN201309UV02;
	protected static org.hl7.v3.types.MCCIIN000002UV01 returnedValueOfPixManagerPRPAIN201302UV02;
	protected static org.hl7.v3.types.MCCIIN000002UV01 returnedValueOfPixManagerPRPAIN201304UV02;
	protected static org.hl7.v3.types.MCCIIN000002UV01 returnedValueOfPixManagerPRPAIN201301UV02;

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.openhie.openpixpdq.services.PIXManagerPortType#pixManagerPRPAIN201309UV02
	 * (org.hl7.v3.types.PRPAIN201309UV02 body )*
	 */
	public org.hl7.v3.types.PRPAIN201310UV02 pixManagerPRPAIN201309UV02(
			org.hl7.v3.types.PRPAIN201309UV02 body) {
		LOG.info("Executing operation pixManagerPRPAIN201309UV02");
		System.out.println(body);
		try {
			org.hl7.v3.types.PRPAIN201310UV02 _return = returnedValueOfPixManagerPRPAIN201309UV02;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.openhie.openpixpdq.services.PIXManagerPortType#pixManagerPRPAIN201302UV02
	 * (org.hl7.v3.types.PRPAIN201302UV02 body )*
	 */
	public org.hl7.v3.types.MCCIIN000002UV01 pixManagerPRPAIN201302UV02(
			org.hl7.v3.types.PRPAIN201302UV02 body) {
		LOG.info("Executing operation pixManagerPRPAIN201302UV02");
		System.out.println(body);
		try {
			org.hl7.v3.types.MCCIIN000002UV01 _return = returnedValueOfPixManagerPRPAIN201302UV02;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.openhie.openpixpdq.services.PIXManagerPortType#pixManagerPRPAIN201304UV02
	 * (org.hl7.v3.types.PRPAIN201304UV02 body )*
	 */
	public org.hl7.v3.types.MCCIIN000002UV01 pixManagerPRPAIN201304UV02(
			org.hl7.v3.types.PRPAIN201304UV02 body) {
		LOG.info("Executing operation pixManagerPRPAIN201304UV02");
		System.out.println(body);
		try {
			org.hl7.v3.types.MCCIIN000002UV01 _return = returnedValueOfPixManagerPRPAIN201304UV02;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.openhie.openpixpdq.services.PIXManagerPortType#pixManagerPRPAIN201301UV02
	 * (org.hl7.v3.types.PRPAIN201301UV02 body )*
	 */
	public org.hl7.v3.types.MCCIIN000002UV01 pixManagerPRPAIN201301UV02(
			org.hl7.v3.types.PRPAIN201301UV02 body) {
		LOG.info("Executing operation pixManagerPRPAIN201301UV02");
		System.out.println(body);
		try {
			org.hl7.v3.types.MCCIIN000002UV01 _return = returnedValueOfPixManagerPRPAIN201301UV02;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}
}
