
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gov.samhsa.acs.trypolicy.wsclient;

import gov.samhsa.acs.pep.ws.contract.TryPolicyPortType;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-06T14:17:35.251-05:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "TryPolicyService",
                      portName = "TryPolicyServicePort",
                      targetNamespace = "http://acs.samhsa.gov/pep/ws/contract",
                      wsdlLocation = "classpath:TryPolicy.wsdl",
                      endpointInterface = "gov.samhsa.acs.pep.ws.contract.TryPolicyPortType")
                      
public class TryPolicyPortTypeImpl implements TryPolicyPortType {

    private static final Logger LOG = Logger.getLogger(TryPolicyPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see gov.samhsa.acs.pep.ws.contract.TryPolicyPortType#tryPolicy(java.lang.String  c32Xml ,)java.lang.String  xacmlPolicy )*
     */
    public java.lang.String tryPolicy(java.lang.String c32Xml,java.lang.String xacmlPolicy, java.lang.String purposeOfUse) { 
        LOG.info("Executing operation tryPolicy");

        String returnedValue = returnedValueOfTryPolicy;

        try {
            java.lang.String _return = returnedValue;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    public static String returnedValueOfTryPolicy = "";

}
