-- Initial categories that are driven by Federal and State jurisdictional type
UPDATE value_set_category SET is_federal = TRUE WHERE code = 'ETH';
UPDATE value_set_category SET is_federal = FALSE WHERE code = 'GDIS';
UPDATE value_set_category SET is_federal = FALSE WHERE code = 'HIV';
UPDATE value_set_category SET is_federal = FALSE WHERE code = 'PSY';
UPDATE value_set_category SET is_federal = FALSE WHERE code = 'SEX';
UPDATE value_set_category SET is_federal = TRUE WHERE code = 'ALC';
UPDATE value_set_category SET is_federal = FALSE WHERE code = 'COM';
UPDATE value_set_category SET is_federal = FALSE WHERE code = 'ADD';

-- Initial Valueset Category Display Order
UPDATE value_set_category SET display_order = '1' WHERE code = 'ETH';
UPDATE value_set_category SET display_order = '5' WHERE code = 'GDIS';
UPDATE value_set_category SET display_order = '4' WHERE code = 'HIV';
UPDATE value_set_category SET display_order = '3' WHERE code = 'PSY';
UPDATE value_set_category SET display_order = '7' WHERE code = 'SEX';
UPDATE value_set_category SET display_order = '2' WHERE code = 'ALC';
UPDATE value_set_category SET display_order = '6' WHERE code = 'COM';
UPDATE value_set_category SET display_order = '8' WHERE code = 'ADD';

-- Modify names and descriptions
UPDATE value_set_category SET name = 'Drug use information', description = 'Drug abuse or substance abuse is the use of mood-altering substances that interfere with or have a negative effect on a person’s life. These include negative effects on a person’s physical, psychological, social, emotional, occupational, and educational well-being. Drug abuse is characterized by dysfunction and negative consequences. Most drugs of abuse are mood altering (they change a person’s mood or feeling), and fall in three categories: stimulants, depressants, and hallucinogens.' WHERE code = 'ETH';
UPDATE value_set_category SET name = 'Genetic disease information', description = 'A genetic disease is a medical disorder that is caused by an abnormality in an individual’s genome, which is the person’s entire genetic makeup. The abnormality can range from minor to major and severe. Some genetic disorders are inherited from parents. Other genetic disorders are caused by changes or mutations in a preexisting gene or a group of genes. Such mutations can occur randomly or due to certain types of environmental exposure.' WHERE code = 'GDIS';
UPDATE value_set_category SET name = 'HIV/AIDS information', description = 'Human immunodeficiency virus (HIV) is a virus that weakens a person’s immune system by destroying important cells that fight disease and infection. HIV infection typically begins with flu-like symptoms followed by a long symptom-free period. HIV can be controlled with antiretroviral therapy. Untreated, HIV can advance to acquire immunodeficiency syndrome (AIDS), the most severe phase of HIV infection. People with AIDS have such badly damaged immune systems that they get an increasing number of severe illnesses, which can lead to death.' WHERE code = 'HIV';
UPDATE value_set_category SET name = 'Mental health information', description = 'Mental illness or a psychiatric disorder is a condition that affects a person’s thinking, feeling, or mood, and may affect his or her ability to relate to others and function well on a daily basis. Mental illnesses are medical conditions that often cause a diminished ability to cope with the ordinary demands of life. Like other medical disorders, mental illness ranges from mild to severe. There is a wide variety of treatments for mental illnesses.' WHERE code = 'PSY';
UPDATE value_set_category SET name = 'Sexuality and reproductive health information', description = 'Good sexual and reproductive health is a state of complete physical, mental, and social well-being in all matters relating to the reproductive system, at all stages of life. It implies that people are able to have a satisfying and safe sex life, the capacity to reproduce, and the freedom to decide if, when, and how often to do so. Similarly, sexual health is a state of physical, emotional, and social well-being in relation to sexuality. It is not simply the absence of disease, dysfunction, or infirmity.' WHERE code = 'SEX';
UPDATE value_set_category SET name = 'Alcohol use and Alcoholism Information', description = 'Alcohol abuse is the use of alcohol in such a way that it interferes with or has a negative effect on a person’s life. These include negative effects on a person’s physical, psychological, social, emotional, occupational, and educational well-being. Alcoholism or alcohol addiction is a primary, chronic, and disabling disorder that involves compulsion, loss of control, and continued use despite negative consequences. Genetic, psychosocial, and environmental factors influence its development and outcome.' WHERE code = 'ALC';
UPDATE value_set_category SET name = 'Communicable disease information', description = 'Communicable diseases, also known as infectious diseases are illnesses that result from the infection, presence, and growth of organisms and microorganisms such as bacteria, viruses, fungi, and parasites. They can be spread, directly or indirectly, from one person to another.' WHERE code = 'COM';
UPDATE value_set_category SET name = 'Addictions information', description = 'Addiction is a primary, chronic, relapsing, and disabling substance use disorder that involves compulsion, loss of control, and continued use despite negative consequences. Genetic, psychosocial, and environmental factors influence its development and outcome. Addiction is a progressive disorder, meaning it gets worse over time, not better.' WHERE code = 'ADD';