CREATE TABLE `pcm`.`attested_consent` (`id` BIGINT AUTO_INCREMENT NOT NULL, `attested_date_time` datetime(6) NULL, `attester_by_user` VARCHAR(255) NOT NULL, `attester_email` VARCHAR(255) NOT NULL, `attester_first_name` VARCHAR(255) NOT NULL, `attester_last_name` VARCHAR(255) NOT NULL, `attester_middle_name` VARCHAR(255) NOT NULL, `consent_reference_id` VARCHAR(255) NOT NULL, `attested_pdf_consent` LONGBLOB NULL, `consent_terms_accepted` BIT(1) NULL, `consent_terms_versions` BIGINT NULL, CONSTRAINT `PK_ATTESTED_CONSENT` PRIMARY KEY (`id`));
CREATE TABLE `pcm`.`attested_consent_aud` (`id` BIGINT NOT NULL, `rev` BIGINT NOT NULL, `revtype` TINYINT(3) NULL, `attested_pdf_consent` LONGBLOB NULL, `consent_terms_accepted` BIT(1) NULL, `consent_terms_versions` BIGINT NULL);
CREATE TABLE `pcm`.`attested_consent_revocation` (`id` BIGINT AUTO_INCREMENT NOT NULL, `attested_date_time` datetime(6) NULL, `attester_by_user` VARCHAR(255) NOT NULL, `attester_email` VARCHAR(255) NOT NULL, `attester_first_name` VARCHAR(255) NOT NULL, `attester_last_name` VARCHAR(255) NOT NULL, `attester_middle_name` VARCHAR(255) NOT NULL, `consent_reference_id` VARCHAR(255) NOT NULL, `attested_pdf_consent_revoke` LONGBLOB NULL, `consent_revoke_terms_accepted` BIT(1) NULL, `consent_revocation_terms_versions` BIGINT NULL, CONSTRAINT `PK_ATTESTED_CONSENT_REVOCATION` PRIMARY KEY (`id`));
CREATE TABLE `pcm`.`attested_consent_revocation_aud` (`id` BIGINT NOT NULL, `rev` BIGINT NOT NULL, `revtype` TINYINT(3) NULL, `attested_pdf_consent_revoke` LONGBLOB NULL, `consent_revoke_terms_accepted` BIT(1) NULL, `consent_revocation_terms_versions` BIGINT NULL);
CREATE TABLE `pcm`.`consent_revocation_terms_versions_aud` (`id` BIGINT NOT NULL, `rev` BIGINT NOT NULL, `revtype` TINYINT(3) NULL, `added_date_time` datetime(6) NULL, `consent_revoke_terms_text` TEXT NULL, `version_disabled` BIT(1) NULL);
CREATE TABLE `pcm`.`consent_terms_versions_aud` (`id` BIGINT NOT NULL, `rev` BIGINT NOT NULL, `revtype` TINYINT(3) NULL, `added_date_time` datetime(6) NULL, `consent_terms_text` TEXT NULL, `version_disabled` BIT(1) NULL);
ALTER TABLE `pcm`.`consent` ADD `un_attested_pdf_consent` LONGBLOB NULL;
ALTER TABLE `pcm`.`consent` ADD `un_attested_pdf_consent_revoke` LONGBLOB NULL;
ALTER TABLE `pcm`.`consent` ADD `attested_consent` BIGINT NULL;
ALTER TABLE `pcm`.`consent` ADD `attested_consent_revocation` BIGINT NULL;
ALTER TABLE `pcm`.`consent_aud` ADD `attested_consent` BIGINT NULL;
ALTER TABLE `pcm`.`consent_aud` ADD `attested_consent_mod` BIT(1) NULL;
ALTER TABLE `pcm`.`consent_aud` ADD `attested_consent_revocation` BIGINT NULL;
ALTER TABLE `pcm`.`consent_aud` ADD `attested_consent_revocation_mod` BIT(1) NULL;
ALTER TABLE `pcm`.`attested_consent_aud` ADD PRIMARY KEY (`id`, `rev`);
ALTER TABLE `pcm`.`attested_consent_revocation_aud` ADD PRIMARY KEY (`id`, `rev`);
ALTER TABLE `pcm`.`consent_revocation_terms_versions_aud` ADD PRIMARY KEY (`id`, `rev`);
ALTER TABLE `pcm`.`consent_terms_versions_aud` ADD PRIMARY KEY (`id`, `rev`);
CREATE INDEX `FK_2c5sw8fng3ts7ypvcsly3mmrv` ON `pcm`.`attested_consent`(`consent_terms_versions`);
CREATE INDEX `FK_36xsx1ogimcd4ierldfrx3xx` ON `pcm`.`attested_consent_aud`(`rev`);
CREATE INDEX `FK_8qald2aawsaaorsk5ibvf7fdf` ON `pcm`.`attested_consent_revocation`(`consent_revocation_terms_versions`);
CREATE INDEX `FK_eado69rpnbk420djuiyimklt` ON `pcm`.`consent_terms_versions_aud`(`rev`);
CREATE INDEX `FK_j7r3tvx6e3py1dxj7k6pwni9` ON `pcm`.`consent_revocation_terms_versions_aud`(`rev`);
CREATE INDEX `FK_jgydfpv7sr5yqqwbo7i6069qt` ON `pcm`.`consent`(`attested_consent`);
CREATE INDEX `FK_puellwq2wvkqfkl5oxqnq3vlv` ON `pcm`.`consent`(`attested_consent_revocation`);
CREATE INDEX `FK_tajsbd7r3ehpr60f5mj307r4r` ON `pcm`.`attested_consent_revocation_aud`(`rev`);
ALTER TABLE `pcm`.`attested_consent` ADD CONSTRAINT `FK_2c5sw8fng3ts7ypvcsly3mmrv` FOREIGN KEY (`consent_terms_versions`) REFERENCES `pcm`.`consent_terms_versions` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `pcm`.`attested_consent_aud` ADD CONSTRAINT `FK_36xsx1ogimcd4ierldfrx3xx` FOREIGN KEY (`rev`) REFERENCES `pcm`.`revinfo` (`rev`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `pcm`.`attested_consent_revocation` ADD CONSTRAINT `FK_8qald2aawsaaorsk5ibvf7fdf` FOREIGN KEY (`consent_revocation_terms_versions`) REFERENCES `pcm`.`consent_revocation_terms_versions` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `pcm`.`consent_terms_versions_aud` ADD CONSTRAINT `FK_eado69rpnbk420djuiyimklt` FOREIGN KEY (`rev`) REFERENCES `pcm`.`revinfo` (`rev`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `pcm`.`consent_revocation_terms_versions_aud` ADD CONSTRAINT `FK_j7r3tvx6e3py1dxj7k6pwni9` FOREIGN KEY (`rev`) REFERENCES `pcm`.`revinfo` (`rev`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `pcm`.`consent` ADD CONSTRAINT `FK_jgydfpv7sr5yqqwbo7i6069qt` FOREIGN KEY (`attested_consent`) REFERENCES `pcm`.`attested_consent` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `pcm`.`consent` ADD CONSTRAINT `FK_puellwq2wvkqfkl5oxqnq3vlv` FOREIGN KEY (`attested_consent_revocation`) REFERENCES `pcm`.`attested_consent_revocation` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `pcm`.`attested_consent_revocation_aud` ADD CONSTRAINT `FK_tajsbd7r3ehpr60f5mj307r4r` FOREIGN KEY (`rev`) REFERENCES `pcm`.`revinfo` (`rev`) ON UPDATE NO ACTION ON DELETE NO ACTION;